### ISSUE TITLE
Set current player name via admin page

### ISSUE THREAD

**Issue by ItsElaineTime** [ArdentHeavyIndustries/flame.vision#11]

**Comment by ItsElaineTime** [comment]
b44e270

**Comment by djcapelis** [comment]
There is no such thing as remove player in the API.  Please collapse "set player" and "remove player" to one "change player" option.

**Comment by djcapelis** [comment]
(We could also change the backend API, which wouldn't be the worst idea.  But it'll need to be a separate call.  The thing is if we did that you'd need to call *both* on a player change, but if you remove and then add, you'd need to call *just* one or the other.  In short there's not a whole lot of state kept server side about this, we just shove whatever the existing player name is into the leaderboard.  When you call a remove, the backend doesn't see the difference between that and a player that we should save the score of.  We could be somewhat smarter here, but I'd prefer not to be?  If we're taking a break, we can just switch running to false.  Or have a separate running = break or something?)

**Comment by paulymer** [comment]
Oh oh sorry. Remove player doesn't delete anything, it sets the current player to the empty string, so in case you're running but taking a break or something you can clear the current player name.

The front-end sees the empty string and sets a placeholder. I'll rename it to Set No Player or something like that.

**Comment by ItsElaineTime** [comment]
Hmmm yeah okay setting not running makes sense. I'll pull the button.

**Comment by djcapelis** [comment]
Thanks! 👍
