### ISSUE TITLE
Add Dansk localized strings

### ISSUE THREAD

**Issue by ItsElaineTime** [ArdentHeavyIndustries/flame.vision#18]

**Comment by djcapelis** [comment]
Do we have a list of English strings to send to Martin so he can help us translate?

**Comment by avalkyrie** [comment]
See the top of flame.js, we've pulled all of the user facing strings into some json. These strings are not final or complete, but we can send them so he can get started. In particular we should review the cookie message if we plan to translate that.

**Comment by djcapelis** [comment]
Awesome, sent to Martin
