### ISSUE TITLE
Show leaders?

### ISSUE THREAD

**Issue by ItsElaineTime** [ArdentHeavyIndustries/flame.vision#9]
How do we calculate the leader board? Where do we display them?

**Comment by djcapelis** [comment]
I believe the backend API endpoint is there, but we don't currently populate due to #20.  Not sure if the frontend implements yet.

**Comment by ItsElaineTime** [comment]
It doesn't. I'm thinking it'll be a list that's displayed just above the Ardent logo, both when running and not.
